BUMPER_TO_CENTER_DIST = 0.17
CAMERA_MODE = 0
CIRCLE_MIN_AREA = 5
CIRCLE_MIN_DISTANCE = 1
CIRCLE_PATTERN_HEIGHT = 3
CIRCLE_PATTERN_WIDTH = 8
TARGET_DIST = 0.10

# Control params
ANGLE_THRESHOLD = 1.0
DISTANCE_THRESHOLD = 0.01
V_CONSTANT = 0.4
V_CORRECTION = 0.75
W_CONSTANT = 0.4
W_CORRECTION = 0.5
